easy_internship/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.views.static import serve as static_serve
from django_nyt.urls import get_pattern as get_nyt_pattern
from rest_framework import routers

from userena import views as userena_views
from accounts.views import SignupWrapper, ProfileEditWrapper, ProfileDetailWrapper, ResendConfirmationKey, \
    ResendConfirmationKeyComplete
from accounts.forms import ChangeInternEmailForm
from accounts.urls import api_urls as accounts_urls
from leaves.urls import api_urls as leaves_urls
from rotations.urls import api_urls as rotations_urls
from hospitals.urls import api_urls as hospitals_urls
from months.urls import api_urls as months_urls
from misc.urls import api_urls as misc_urls

from . import views

api_urls = (
    hospitals_urls,
    months_urls,
    rotations_urls,
    accounts_urls,
    leaves_urls,
    misc_urls,
)

router = routers.DefaultRouter()
for app in api_urls:
    for urlconf in app:
        router.register(*urlconf)


urlpatterns = [
    url(r'^$', views.index, name="index"),

    url(r'^api/', include(router.urls)),
    url(r'^messages/$', views.GetMessages.as_view()),
    url(r'^notifications/', get_nyt_pattern()),

    url(r'^accounts/activate/(?P<activation_key>\w+)/$', userena_views.activate, {'success_url': '/'}),
    url(r'^accounts/resend/$', ResendConfirmationKey.as_view(), name="resend_activation"),
    url(r'^accounts/resend/complete/$', ResendConfirmationKeyComplete.as_view(), name="resend_activation_complete"),
    url(r'^accounts/(?P<username>[\@\.\w-]+)/email/$', userena_views.email_change, {'email_form': ChangeInternEmailForm}),
    url(r'^accounts/(?P<username>[\@\.\w-]+)/edit/$', ProfileEditWrapper.as_view()),
    url(r'^accounts/(?P<username>(?!(signout|signup|signin)/)[\@\.\w-]+)/$', ProfileDetailWrapper.as_view()),
    url(r'^accounts/signup/$', SignupWrapper.as_view()),
    url(r'^accounts/', include('userena.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    # media files (user-uploaded files)
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', static_serve, {
        'document_root': settings.MEDIA_ROOT})
    ]

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

misc/urls.py
from misc import views
api_urls = (
    (r'^announcements/$', views.AnnouncementsViewSet,'announcements'),
    (r'^users/$', views.UserViewSet),
)

accounts/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from month.models import MonthField
from userena.models import UserenaBaseProfile

from accounts.managers import UniversityManager, BatchQuerySet


class Profile(UserenaBaseProfile):
    user = models.OneToOneField(User, related_name="profile")

    STAFF = "staff"
    INTERN = "intern"

    ROLE_CHOICES = (
        (STAFF, "Staff member"),
        (INTERN, "Intern"),
    )

    role = models.CharField(max_length=8, choices=ROLE_CHOICES)
    ar_first_name = models.CharField(max_length=32)
    ar_father_name = models.CharField(max_length=32)
    ar_grandfather_name = models.CharField(max_length=32)
    ar_last_name = models.CharField(max_length=32)
    en_first_name = models.CharField(max_length=32)
    en_father_name = models.CharField(max_length=32)
    en_grandfather_name = models.CharField(max_length=32)
    en_last_name = models.CharField(max_length=32)

    def get_ar_full_name(self):
        return " ".join([self.ar_first_name, self.ar_father_name, self.ar_grandfather_name[0], self.ar_last_name])

    def get_en_full_name(self):
        return " ".join([self.en_first_name, self.en_father_name, self.en_grandfather_name[0], self.en_last_name])

    def clean(self):
        # TODO: Force having an intern profile when role=intern (Perhaps overriding the save method would be better)
        pass

    def __unicode__(self):
        return "Profile of user: %s" % self.user.username


class Intern(models.Model):
    profile = models.OneToOneField(Profile, related_name="intern")

    batch = models.ForeignKey("Batch", related_name='interns')
    university = models.ForeignKey("University", related_name='interns')

    student_number = models.CharField(max_length=9, blank=True, null=True)
    badge_number = models.CharField(max_length=9, blank=True, null=True)
    alt_email = models.EmailField(blank=True, null=True)
    phone_number = models.CharField(max_length=16, blank=True)
    mobile_number = models.CharField(max_length=16)
    address = models.CharField(max_length=128)

    id_number = models.CharField(max_length=10)
    id_image = models.ImageField(upload_to='saudi_ids')

    has_passport = models.NullBooleanField(default=True)
    passport_number = models.CharField(max_length=10, blank=True, null=True)
    passport_image = models.ImageField(upload_to='passports', blank=True, null=True)
    passport_attachment = models.FileField(upload_to='passport_attachments', blank=True, null=True)

    medical_record_number = models.CharField(max_length=10, blank=True, null=True)
    medical_checklist = models.FileField(upload_to='medical_checklists', blank=True, null=True)

    contact_person_name = models.CharField(max_length=64)
    contact_person_relation = models.CharField(max_length=32)
    contact_person_mobile = models.CharField(max_length=16)
    contact_person_email = models.EmailField(max_length=64)

    gpa = models.FloatField(validators=[MaxValueValidator(5.0), MinValueValidator(0.0)])
    academic_transcript = models.FileField(upload_to='academic_transcripts', blank=True, null=True)
    graduation_date = MonthField(blank=True, null=True)

    @property
    def is_ksauhs_intern(self):
        return self.university.is_ksauhs

    @property
    def is_agu_intern(self):
        return self.university.is_agu

    @property
    def is_outside_intern(self):
        return self.university.is_outside

    def __unicode__(self):
        return "Intern profile of user: %s" % self.profile.user.username


class University(models.Model):
    name = models.CharField(max_length=60)
    abbreviation = models.CharField(max_length=10)
    city = models.CharField(max_length=20)
    country = models.CharField(max_length=20)
    internship_phone = models.CharField(max_length=16)
    internship_fax = models.CharField(max_length=16)
    internship_email = models.EmailField()
    is_ksauhs = models.BooleanField(default=False)
    is_agu = models.BooleanField(default=False)

    objects = UniversityManager()

    @property
    def is_outside(self):
        return not (self.is_ksauhs or self.is_agu)

    def clean(self):
        """
        A university can't have both `is_ksauhs` and `is_agu` flags True at the same time.
        """
        if self.is_ksauhs and self.is_agu:
            raise ValidationError(
                "A university can't be both KSAU-HS and AGU at the same time."
            )

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Universities"


class Batch(models.Model):
    name = models.CharField(max_length=20)
    abbreviation = models.CharField(max_length=10)
    is_ksauhs = models.BooleanField(default=False)
    is_agu = models.BooleanField(default=False)
    start_month = MonthField(help_text="The month on which the batch is expected to start their medical internship")

    objects = BatchQuerySet.as_manager()

    @property
    def is_outside(self):
        return not (self.is_ksauhs or self.is_agu)

    def clean(self):
        """
        (1)
        A batch can't have both `is_ksauhs` and `is_agu` flags True at the same time.

        (2)
        Batches of the same kind (ksauhs, agu, outside) shouldn't overlap; i.e. each batch has a 12-month period
        beginning at the start_month that should not intersect with that of any other batches of the same kind.

        This is particularly important when sorting interns into batches upon sign-up, since each intern is sorted
        into the correct batch based his/her internship start_month. Having overlapping batches will result in
        failure to locate the intern into the right batch.
        """
        errors = []

        # (1)
        if self.is_ksauhs and self.is_agu:
            errors.append(
                ValidationError(
                    "A batch can't be both a KSAU-HS batch and an AGU batch at the same time."
                )
            )

        # (2)
        # Get a list of the months already reserved by existing batches of the same kind
        if self.is_ksauhs:
            batches = self.__class__.objects.ksauhs()
        elif self.is_agu:
            batches = self.__class__.objects.agu()
        else:
            batches = self.__class__.objects.outside()

        # Exclude self if it's in the db
        if self.id:
            batches = batches.exclude(id=self.id)

        start_months = batches.values_list('start_month', flat=True)
        all_months = list()

        for month in start_months:
            for add in range(12):
                all_months.append(month + add)

        # Check that the current batch's start month doesn't exist in `all_months`
        if self.start_month in all_months:
            errors.append(
                ValidationError(
                    "Can't have two overlapping batches of the same type. Please change the batch's start "
                    "month so it's within 12 months of any other batch's start month."
                )
            )
        if errors:
            raise ValidationError(errors)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Batches"
        ordering = ('-start_month',)

easy_internship/views.py
from django.contrib.messages.api import get_messages
from django.shortcuts import render
from rest_framework import views
from rest_framework.response import Response

from accounts.models import Profile
from easy_internship.serializers import MessageSerializer


def index(request):
    """
    Loads the main page.
    """
    if request.GET.get("role") and request.user.is_superuser:
        role = request.GET.get("role")
    else:
        if request.user.has_perm("planner.view_intern_site"):
            role = Profile.INTERN
        elif request.user.has_perm("planner.view_staff_site"):
            role = Profile.STAFF
        else:
            role = "outsider"
    # role = request.GET.get("role") or "intern"
    context = {"role": role}
    return render(request, "index.html", context)


class GetMessages(views.APIView):
    def get(self, request):
        messages = list(get_messages(request))
        serialized = MessageSerializer(messages, many=True)
        return Response(serialized.data)

easy_internship/templates/components/content.html
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <div ng-view{% if not role == "staff" %} class="container"{% endif %}>
    <!-- Content Header (Page header) -->
    <section class="content-header">

    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Your Page Content Here -->

    </section>
    <!-- /.content -->
    </div>
  </div>
  <!-- /.content-wrapper -->

easy_internship/templates/components/control-sidebar.html
  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
      <li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
      <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
      <!-- Home tab content -->
      <div class="tab-pane active" id="control-sidebar-home-tab">
        <h3 class="control-sidebar-heading">Recent Activity</h3>
        <ul class="control-sidebar-menu">
          <li>
            <a href="javascript::;">
              <i class="menu-icon fa fa-birthday-cake bg-red"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                <p>Will be 23 on April 24th</p>
              </div>
            </a>
          </li>
        </ul>
        <!-- /.control-sidebar-menu -->

        <h3 class="control-sidebar-heading">Tasks Progress</h3>
        <ul class="control-sidebar-menu">
          <li>
            <a href="javascript::;">
              <h4 class="control-sidebar-subheading">
                Custom Template Design
                <span class="label label-danger pull-right">70%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
              </div>
            </a>
          </li>
        </ul>
        <!-- /.control-sidebar-menu -->

      </div>
      <!-- /.tab-pane -->
      <!-- Stats tab content -->
      <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
      <!-- /.tab-pane -->
      <!-- Settings tab content -->
      <div class="tab-pane" id="control-sidebar-settings-tab">
        <form method="post">
          <h3 class="control-sidebar-heading">General Settings</h3>

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Report panel usage
              <input type="checkbox" class="pull-right" checked>
            </label>

            <p>
              Some information about this general settings option
            </p>
          </div>
          <!-- /.form-group -->
        </form>
      </div>
      <!-- /.tab-pane -->
    </div>
  </aside>
  <!-- /.control-sidebar -->
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>

easy_internship/templates/components/footer.html
  <!-- Main Footer -->
  <footer class="main-footer">
    {% if not role == "staff" %}<div class="container">{% endif %}
    <!-- To the right -->
    <div class="pull-right hidden-xs">

      <a class="btn btn-sm btn-flat btn-default" href="http://com.ksau-hs.edu.sa/eng/index.php?option=com_content&view=article&id=269&Itemid=458">
        <i class="fa fa-globe"></i>
      </a>

      <a class="btn btn-sm btn-flat btn-default" href="mailto:miu-com-r@ksau-hs.edu.sa">
        <i class="fa fa-envelope-o"></i>
      </a>

    </div>
    <!-- Default to the left -->
    <strong>College of Medicine</strong> | King Saud bin Abdulaziz University for Health Sciences
    {% if not role == "staff" %}</div>{% endif %}
  </footer>

easy_internship/templates/components/header-topnav.html
{% load staticfiles %}{% load sitetree %}
<header class="main-header">
  <nav class="navbar navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <a href="#/" class="navbar-brand"><b>Easy</b>Internship</a>
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
          <i class="fa fa-bars"></i>
        </button>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse pull-left" id="navbar-collapse" ng-controller="MenuCtrl">

        {% sitetree_menu from "interntree" include "trunk" template "sitetree/menu_bootstrap3_angular.html" %}

      </div><!-- /.navbar-collapse -->
      {% include 'components/right-navbar.html' %}
    </div><!-- /.container-fluid -->
  </nav>
</header>

easy_internship/templates/components/header.html
{% load staticfiles %}
<!-- Main Header -->
  <header class="main-header">

    <!-- Logo -->
    <a href="#/" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>E</b>I</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>Easy</b>Internship</span>
    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
      <!-- Sidebar toggle button-->
      <a href="" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>

      {% include 'components/right-navbar.html' %}
    </nav>
  </header>

easy_internship/templates/components/right-navbar.html
{% load staticfiles %}
<!-- Navbar Right Menu -->
<div class="navbar-custom-menu">
  <ul class="nav navbar-nav">

    {% verbatim %}
    <!-- Notifications Menu -->
    <li class="dropdown notifications-menu" ng-controller="NotificationCtrl">
      <!-- Menu toggle button -->
      <a href="" class="dropdown-toggle" data-toggle="dropdown">
        <i class="fa fa-bell-o"></i>
        <span ng-show="total_count > 0" class="label label-danger notification-cnt" ng-cloak>{{ total_count }}</span>
      </a>
      <ul class="dropdown-menu">
        <li class="header">Notifications</li>
        <li>
          <!-- Inner Menu: contains the notifications -->
          <ul class="menu">
            <li class="notification-before-list"></li>
            <li ng-if="!notifications || notifications.length == 0" class="notifications-empty">
              <a>
                <em>No notifications</em>
              </a>
            </li>
            <li ng-repeat="n in notifications">
              <a href="" style="white-space: normal;" ng-click="nyt_read_notification(n)">
                <div>{{ n.message }}</div>
                <div class="since">{{ n.occurrences_msg }} - {{ n.since }}</div>
              </a>
            </li>
          </ul>
        </li>
        <li class="footer">
          <a href="" ng-click="nyt_mark_all_read()">
            <i class="fa fa-check"></i>
            Clear notifications list
          </a>
          <!--<a href="#">View all</a>-->
        </li>
      </ul>
    </li>
    {% endverbatim %}

    <li class="dropdown messages-menu">
      <!-- Menu toggle button -->
      <a href="" class="dropdown-toggle" data-toggle="dropdown">
        <i class="fa fa-question-circle"></i>
      </a>
      <ul class="dropdown-menu">
        <li class="header text-bold">Need help? Have feedback?</li>
        <li>
          <p class="text-center">
            <br>
            For any assistance, questions, or feedback regarding Easy Internship, don't hesitate to contact us at<br>
            <span class="text-bold text-light-blue" style="font-size: 1.2em;">
              <a href="mailto:{{ SUPPORT_EMAIL_ADDRESS }}">{{ SUPPORT_EMAIL_ADDRESS }}</a>
            </span>
            <br>
            <br>
          </p>
        </li>
      </ul>
    </li>

    <!-- User Account Menu -->
    <li class="dropdown user user-menu">
      <!-- Menu Toggle Button -->
      <a href="" class="dropdown-toggle" data-toggle="dropdown">
        <!-- The user image in the navbar-->
        <img src="{{ user.profile.get_mugshot_url }}" class="user-image" alt="User Image">
        <!-- hidden-xs hides the username on small devices so only the image appears. -->
        <span class="hidden-xs">{{ user.profile.get_en_full_name }}</span>
      </a>
      <ul class="dropdown-menu">
        <!-- The user image in the menu -->
        <li class="user-header">
          <img src="{{ user.profile.get_mugshot_url }}" class="img-circle" alt="User Image">
          <p>
            {{ user.profile.get_en_full_name }} - {{ user.profile.get_role_display }}
            <small>Member since {{ user.date_joined|date }}</small>
          </p>
        </li>
        {% if False %}
        <!-- Menu Body -->
        <li class="user-body">
          <div class="col-xs-4 text-center">
            <a href="#">Followers</a>
          </div>
          <div class="col-xs-4 text-center">
            <a href="#">Sales</a>
          </div>
          <div class="col-xs-4 text-center">
            <a href="#">Friends</a>
          </div>
        </li>
        {% endif %}
        <!-- Menu Footer-->
        <li class="user-footer">
          <div class="pull-left">
            <a href="{% url 'userena_profile_detail' user.username %}" class="btn btn-default btn-flat">Profile</a>
          </div>
          <div class="pull-right">
            <a href="{% url 'userena_signout' %}" class="btn btn-default btn-flat">Sign out</a>
          </div>
        </li>
      </ul>
    </li>
  {% if False %}
    <!-- Control Sidebar Toggle Button -->
    <li>
      <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
    </li>
  {% endif %}
  </ul>
</div><!-- /.navbar-custom-menu -->

easy_internship/templates/components/scripts.html
{% load staticfiles %}
<!-- Angular 1.5.6 libraries -->
<script src="{% static 'bower_components/angular-resource/angular-resource.min.js' %}"></script>
<script src="{% static 'bower_components/angular-route/angular-route.min.js' %}"></script>
<script src="{% static 'bower_components/angular-touch/angular-touch.min.js' %}"></script>
<script src="{% static 'bower_components/angular-animate/angular-animate.min.js' %}"></script>
<script src="{% static 'bower_components/angular-sanitize/angular-sanitize.min.js' %}"></script>
<!-- Angular UI: Bootstrap -->
<script src="{% static 'bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js' %}"></script>
<!-- Datatables -->
<script src="{% static 'bower_components/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'bower_components/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
<!-- Angular Datatables -->
<script src="{% static 'bower_components/angular-datatables/dist/angular-datatables.min.js' %}"></script>
<script src="{% static 'bower_components/angular-datatables/dist/plugins/bootstrap/angular-datatables.bootstrap.min.js' %}"></script>
<!-- Handsontable -->
<script src="{% static 'bower_components/handsontable/dist/handsontable.full.min.js' %}"></script>
<script src="{% static 'bower_components/ngHandsontable/dist/ngHandsontable.min.js' %}"></script>
<!-- ng-file-upload -->
<script src="{% static 'bower_components/ng-file-upload/ng-file-upload-all.min.js' %}"></script>
<!-- ng-scrollbars -->
<script src="{% static 'bower_components/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js' %}"></script>
<script src="{% static 'bower_components/ng-scrollbars/dist/scrollbars.min.js' %}"></script>
<!-- angular-ui-select -->
<script src="{% static 'bower_components/angular-ui-select/dist/select.min.js' %}"></script>
<!-- Moment.js -->
<script src="{% static 'bower_components/moment/min/moment.min.js' %}"></script>
<!-- Toastr -->
<script src="{% static 'bower_components/toastr/toastr.min.js' %}"></script>
<!-- Angular pagination -->
<script src="{% static 'bower_components/angularUtils-pagination/dirPagination.js' %}"></script>
<!-- Angular Chart.js -->
<script src="{% static 'bower_components/chart.js/dist/Chart.min.js' %}"></script>
<script src="{% static 'bower_components/angular-chart.js/dist/angular-chart.min.js' %}"></script>

<!-- AdminLTE App -->
<script src="{% static 'admin-lte/js/app.min.js' %}"></script>

<!-- Django Angular -->
<script src="{% static 'djng/js/django-angular.js' %}"></script>
<!-- Django NYT Scripts -->
<script type="text/javascript">
  URL_NYT_GET_NEW = "{% url "nyt:json_get" %}";
  URL_NYT_MARK_READ = "{% url "nyt:json_mark_read_base" %}";
  URL_NYT_GOTO = "{% url "nyt:goto_base" %}";
</script>

<!-- Angular App -->
<!-- Resources -->
<script src="{% static 'app/resources/ei.hospitals.models.js' %}?v=0005"></script>
<script src="{% static 'app/resources/ei.months.models.js' %}?rel=1506241820987"></script>
<script src="{% static 'app/resources/ei.rotations.models.js' %}?rel=1498746955411"></script>
<script src="{% static 'app/resources/ei.accounts.models.js' %}?rel=1498746955411"></script>
<script src="{% static 'app/resources/ei.leaves.models.js' %}?rel=1505014661209"></script>
<!-- Directives -->
<script src="{% static 'app/directives/ei.rotations.directives.js' %}?v=0012"></script>
<script src="{% static 'app/directives/ei.months.directives.js' %}?rel=1506166916421"></script>
<script src="{% static 'app/directives/ei.leaves.directives.js' %}?rel=1506114197800"></script>
<!-- Utilities -->
<script src="{% static 'app/resources/ei.interceptors.js' %}"></script>
<script src="{% static 'app/resources/ei.utils.js' %}?v=0001"></script>
<!-- Controllers -->
{% if role == 'intern' %}
<script src="{% static 'app/intern/ei.intern.hospitals.js' %}?v=0003"></script>
<script src="{% static 'app/intern/ei.intern.months.js' %}?rel=1506241820986"></script>
<script src="{% static 'app/intern/ei.intern.rotations.js' %}?v=0014"></script>
<script src="{% static 'app/intern/ei.intern.leaves.js' %}?rel=1506239095806"></script>
<script src="{% static 'app/intern/ei.intern.js' %}?v=0004"></script>
{% elif role == 'staff' %}
<script src="{% static 'app/staff/ei.staff.accounts.js' %}?rel=1506235365812"></script>
<script src="{% static 'app/staff/ei.staff.hospitals.js' %}?v=0001"></script>
<script src="{% static 'app/staff/ei.staff.rotations.js' %}?rel=1500118799370"></script>
<script src="{% static 'app/staff/ei.staff.leaves.js' %}?rel=1503603970322"></script>
<script src="{% static 'app/staff/ei.staff.js' %}?v=0004"></script>
{% elif role == 'outsider' %}
<script src="{% static 'app/outsider/ei.outsider.js' %}?v=0002"></script>
{% endif %}

easy_internship/templates/components/sidebar.html
{% load staticfiles %}{% load sitetree %}
<!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar" ng-controller="MenuCtrl">

      <!-- Sidebar user panel (optional) -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="{{ user.profile.get_mugshot_url }}" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>Medical Internship Unit</p>
          <!-- Status -->
          <a href="#"><i class="fa fa-circle text-success"></i> Control Panel</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      {% sitetree_menu from "stafftree" include "trunk" template "sitetree/sidebar_bootstrap3_angular.html" %}
      <!-- /.sidebar-menu -->

    </section>
    <!-- /.sidebar -->
  </aside>