easy_internship/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.views.static import serve as static_serve
from django_nyt.urls import get_pattern as get_nyt_pattern
from rest_framework import routers

from userena import views as userena_views
from accounts.views import SignupWrapper, ProfileEditWrapper, ProfileDetailWrapper, ResendConfirmationKey, \
    ResendConfirmationKeyComplete
from accounts.forms import ChangeInternEmailForm
from accounts.urls import api_urls as accounts_urls
from leaves.urls import api_urls as leaves_urls
from rotations.urls import api_urls as rotations_urls
from hospitals.urls import api_urls as hospitals_urls
from months.urls import api_urls as months_urls
from misc.urls import api_urls as misc_urls

from . import views

api_urls = (
    hospitals_urls,
    months_urls,
    rotations_urls,
    accounts_urls,
    leaves_urls,
    misc_urls,
)

router = routers.DefaultRouter()
for app in api_urls:
    for urlconf in app:
        router.register(*urlconf)


urlpatterns = [
    url(r'^$', views.index, name="index"),

    url(r'^api/', include(router.urls)),
    url(r'^messages/$', views.GetMessages.as_view()),
    url(r'^notifications/', get_nyt_pattern()),

    url(r'^accounts/activate/(?P<activation_key>\w+)/$', userena_views.activate, {'success_url': '/'}),
    url(r'^accounts/resend/$', ResendConfirmationKey.as_view(), name="resend_activation"),
    url(r'^accounts/resend/complete/$', ResendConfirmationKeyComplete.as_view(), name="resend_activation_complete"),
    url(r'^accounts/(?P<username>[\@\.\w-]+)/email/$', userena_views.email_change, {'email_form': ChangeInternEmailForm}),
    url(r'^accounts/(?P<username>[\@\.\w-]+)/edit/$', ProfileEditWrapper.as_view()),
    url(r'^accounts/(?P<username>(?!(signout|signup|signin)/)[\@\.\w-]+)/$', ProfileDetailWrapper.as_view()),
    url(r'^accounts/signup/$', SignupWrapper.as_view()),
    url(r'^accounts/', include('userena.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    # media files (user-uploaded files)
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', static_serve, {
        'document_root': settings.MEDIA_ROOT})
    ]

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

misc/urls.py
from misc import views
api_urls = (
    (r'^announcements/$', views.AnnouncementsViewSet,'announcements'),
    (r'^users/$', views.UserViewSet),
)

rotations/models.py
from __future__ import unicode_literals

from copy import copy

import itertools
from django.core import validators
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.db import models
from django.db.models.query_utils import Q
from django.utils.crypto import get_random_string
from django_nyt.utils import notify
from month.models import MonthField

from months.models import Internship
from rotations.managers import RotationManager, RotationRequestQuerySet


class Rotation(models.Model):
    internship = models.ForeignKey(Internship, related_name="rotations")
    month = MonthField()
    specialty = models.ForeignKey('hospitals.Specialty', related_name="rotations")
    department = models.ForeignKey('hospitals.Department', related_name="rotations")
    is_elective = models.BooleanField(default=False)
    rotation_request = models.OneToOneField("RotationRequest")

    objects = RotationManager()

    def __unicode__(self):
        return "%s rotation in %s (%s)" % (self.specialty, self.department, self.month)


class RequestedDepartment(models.Model):
    is_in_database = models.BooleanField()
    department = models.ForeignKey('hospitals.Department', related_name="department_requests", null=True, blank=True)

    department_hospital = models.ForeignKey('hospitals.Hospital', null=True, blank=True)
    department_name = models.CharField(max_length=128, blank=True)
    department_specialty = models.ForeignKey('hospitals.Specialty', null=True, blank=True)
    department_contact_name = models.CharField(max_length=128, blank=True)
    department_contact_position = models.CharField(max_length=128, null=True, blank=True)
    department_email = models.EmailField(max_length=128, blank=True)
    department_phone = models.CharField(
        max_length=128,
        blank=True,
        validators=[
            validators.RegexValidator(
                r'^\+\d{12}$',
                code='invalid_phone_number',
                message="Phone number should follow the format +966XXXXXXXXX."
            )
        ]
    )
    department_extension = models.CharField(
        max_length=16,
        blank=True,
        validators=[
            validators.RegexValidator(
                r'^\d{3}\d*$',
                code='invalid_extension',
                message="Extension should be at least 3 digits long."
            )
        ]
    )

    def clean(self):
        """
        Check that *either* of the department field or the department_* details
        fields are filled, but not both or none; and that `is_in_database` flag
        is correctly assigned.
        """
        department_field_filled = self.department is not None
        department_details_filled = all([
            self.department_hospital is not None,
            self.department_name != "",
            self.department_specialty is not None,
            self.department_contact_name != "",
            self.department_contact_position != "",
            self.department_email != "",
            self.department_phone != "",
            self.department_extension != "",
        ])

        if department_field_filled and department_details_filled:
            raise ValidationError("Either an existing department should be chosen, "
                                  "or the details of a new department be filled; but not both.")

        elif not department_field_filled and not department_details_filled:
            raise ValidationError("Either an existing department should be chosen, "
                                  "or the details of a new department be filled.")

        elif department_field_filled and not self.is_in_database:
            raise ValidationError("`is_in_database` flag should be True if an existing department is chosen.")

        elif department_details_filled and self.is_in_database:
            raise ValidationError("`is_in_database` flag should be False if "
                                  "the details of a new department are filled in.")

    def link_to_existing_department(self, department):
        """
        Clears all the department_* details fields and links to an existing department through
         the `department` field.
        """
        from hospitals.models import Department

        if department in Department.objects.all():

            self.department = department
            self.is_in_database = True

            # Empty the department_* details fields
            self.department_hospital = None
            self.department_name = ""
            self.department_specialty = None
            self.department_contact_name = ""
            self.department_contact_position = ""
            self.department_email = ""
            self.department_phone = ""
            self.department_extension = ""

            self.save()
        else:
            raise ObjectDoesNotExist("This department doesn't exist in the database.")

    def add_to_database(self):
        """
        Create a new department based on the data in this request, then link the request to that
        department and clear the department_* details fields.
        """
        from hospitals.models import Department

        if self.department in Department.objects.all():
            raise Exception("Department already exists in database!")  # FIXME: A more accurate exception class?

        new_department = Department.objects.create(  # FIXME: What about the dept. being actually a section of another?
            hospital=self.department_hospital,
            name=self.department_name,
            specialty=self.department_specialty,
            contact_name=self.department_contact_name,
            contact_position=self.department_contact_position,
            email=self.department_email,
            phone=self.department_phone,
            extension=self.department_extension,
        )
        self.link_to_existing_department(new_department)

    def get_department(self):
        """
        Return the `Department` instance if that exists in the database. Otherwise return
        a `Department` object containing all the details from the department_* fields.
        """
        from hospitals.models import Department
        if self.is_in_database:
            return self.department
        else:
            return Department(
                hospital=self.department_hospital,
                name=self.department_name,
                specialty=self.department_specialty,
                contact_name=self.department_contact_name,
                contact_position=self.department_contact_position,
                email=self.department_email,
                phone=self.department_phone,
                extension=self.department_extension,
            )

    def __unicode__(self):
        return self.get_department().name


class RotationRequest(models.Model):
    internship = models.ForeignKey(Internship, related_name="rotation_requests")
    month = MonthField()
    specialty = models.ForeignKey('hospitals.Specialty', related_name="rotation_requests")  # TODO: Is this field really necessary?
    requested_department = models.OneToOneField(RequestedDepartment)
    is_delete = models.BooleanField(
        verbose_name="Is a Cancel Request?",
        default=False
    )  # Flag to determine if this is a "delete" request
    # FIXME: Maybe department & specialty should be optional with delete=True
    is_elective = models.BooleanField(default=False)
    request_memo = models.FileField(null=True, blank=True, upload_to='request_memos')  # required for outside interns
    submission_datetime = models.DateTimeField(auto_now_add=True)

    objects = RotationRequestQuerySet().as_manager()

    PENDING_STATUS = "P"
    FORWARDED_STATUS = "F"
    REVIEWED_STATUS = "R"

    @property
    def is_forwarded(self):
        return hasattr(self, 'forward')

    def validate_request(self):
        """
        Checks that:
        1- The rotation request alters the internship plan in a way that keeps it at 12 rotations or less.
        2- The rotation request alters the internship plan in a way that doesn't exceed the maximum number of months
         for each required specialty.
        """
        predicted_plan = self.get_predicted_plan()
        predicted_plan.validate_internship_plan()

    def get_predicted_plan(self):
        """
        Returns an `Internship` object representing what the internship plan will look like
        if all the rotation requests in this plan request are accepted.
        """
        # Make a list of new rotation objects based on the rotation requests attached to the
        # internship plan
        updated_rotations = [
            Rotation(internship=self.internship,
                     month=request.month,
                     department=request.requested_department.get_department(),
                     specialty=request.specialty,
                     is_elective=request.is_elective)

            for request in self.internship.rotation_requests.open().filter(is_delete=False)
        ]

        # Don't forget this rotation request (self), since it's not yet saved when this is running
        if not self.is_delete:
            updated_rotations.append(
                Rotation(internship=self.internship,
                         month=self.month,
                         department=self.requested_department.get_department(),
                         specialty=self.specialty,
                         is_elective=self.is_elective)
            )

        # Exclude overlapping months
        excluded_months = self.internship.rotation_requests.open().values_list("month", flat=True)

        # To make the final list of the updated rotations, add the existing unaffected rotations to the
        # list of new ones
        updated_rotations.extend(self.internship.rotations.exclude(month__in=excluded_months))

        # Make a copy of the internship object
        predicted = copy(self.internship)
        predicted.pk = None

planner/templates/planner/forms/rotation-request.html
<div class="example-modal">
  <div class="modal">
    <div class="modal-dialog">
      <form name="{{ form.form_name }}" novalidate>
        <div class="modal-content">

          <div class="modal-header">
            {% verbatim %}
            <h3 class="modal-title">Request a rotation for {{ internshipMonth.label }}</h3>
            {% endverbatim %}
          </div>

          <div class="modal-body">

            <p>Please select the specialty and hospital you want to rotate in from the lists below.</p>

            {# FIXME: This is not a DRY solution. There is no need ideally for the fields to be redefined again here. #}

            <div class="has-feedback form-group"><label class="control-label" for="id_department_specialty">Specialty</label><select class="form-control" id="id_department_specialty" name="department_specialty" ng-model="rotationRequestData[&#39;department_specialty&#39;]">
              <option value="" selected="selected">---------</option>
              <option value="1">Internal Medicine</option>
              <option value="2">Surgery</option>
            </select><ul class="djng-form-control-feedback djng-field-errors" ng-show="rotationRequestForm.department_specialty.$dirty" ng-cloak><li ng-show="rotationRequestForm['department_specialty'].$valid" class="valid"></li></ul><ul class="djng-form-control-feedback djng-field-errors" ng-show="rotationRequestForm.department_specialty.$pristine" ng-cloak><li ng-show="rotationRequestForm.department_specialty.$message" class="invalid" ng-bind="rotationRequestForm.department_specialty.$message"></li></ul></div>

            <div class="has-feedback form-group"><label class="control-label" for="id_department_hospital">Hospital</label><select class="form-control" id="id_department_hospital" name="department_hospital" ng-model="rotationRequestData[&#39;department_hospital&#39;]">
              <option value="" selected="selected">---------</option>
              <option value="1">King Abdulaziz Medical City</option>
              <option value="2">King Fahad Medical City</option>
            </select><ul class="djng-form-control-feedback djng-field-errors" ng-show="rotationRequestForm.department_hospital.$dirty" ng-cloak><li ng-show="rotationRequestForm['department_hospital'].$valid" class="valid"></li></ul><ul class="djng-form-control-feedback djng-field-errors" ng-show="rotationRequestForm.department_hospital.$pristine" ng-cloak><li ng-show="rotationRequestForm.department_hospital.$message" class="invalid" ng-bind="rotationRequestForm.department_hospital.$message"></li></ul></div>

            <div ng-if="rotationRequestData.is_in_database == false">

              {% verbatim %}
              <p>
                It appears we don't have the contact details for this specialty's department within the hospital you chose.
                Kindly provide us with these details below.
              </p>
              {% endverbatim %}

              <div class="has-feedback form-group"><label class="control-label" for="id_department_name">Name of Department</label><input class="form-control" id="id_department_name" maxlength="128" name="department_name" ng-maxlength="128" ng-model="rotationRequestData[&#39;department_name&#39;]" type="text" /><ul class="djng-form-control-feedback djng-field-errors" ng-show="rotationRequestForm.department_name.$dirty" ng-cloak><li ng-show="rotationRequestForm['department_name'].$error.maxlength" class="invalid">Ensure this value has at most 128 characters</li><li ng-show="rotationRequestForm['department_name'].$valid" class="valid"></li></ul><ul class="djng-form-control-feedback djng-field-errors" ng-show="rotationRequestForm.department_name.$pristine" ng-cloak><li ng-show="rotationRequestForm.department_name.$message" class="invalid" ng-bind="rotationRequestForm.department_name.$message"></li></ul></div>
              <div class="has-feedback form-group"><label class="control-label" for="id_department_contact_name">Name of Contact Person in the Department</label><input class="form-control" id="id_department_contact_name" maxlength="128" name="department_contact_name" ng-maxlength="128" ng-model="rotationRequestData[&#39;department_contact_name&#39;]" type="text" /><ul class="djng-form-control-feedback djng-field-errors" ng-show="rotationRequestForm.department_contact_name.$dirty" ng-cloak><li ng-show="rotationRequestForm['department_contact_name'].$error.maxlength" class="invalid">Ensure this value has at most 128 characters</li><li ng-show="rotationRequestForm['department_contact_name'].$valid" class="valid"></li></ul><ul class="djng-form-control-feedback djng-field-errors" ng-show="rotationRequestForm.department_contact_name.$pristine" ng-cloak><li ng-show="rotationRequestForm.department_contact_name.$message" class="invalid" ng-bind="rotationRequestForm.department_contact_name.$message"></li></ul></div>
              <div class="has-feedback form-group"><label class="control-label" for="id_department_email">Email</label><input class="form-control" email-pattern="(^[-!#$%&amp;&#39;*+/=?^_`{}|~0-9A-Z]+(\.[-!#$%&amp;&#39;*+/=?^_`{}|~0-9A-Z]+)*@|^&quot;([\001-\010\013\014\016-\037!#-\[\]-\177]|\\[\001-\011\013\014\016-\177])*&quot;@)(localhost$|((?:[A-Z0-9](?:[A-Z0-9-]{0,61}[A-Z0-9])?\.)+)(?:[A-Z0-9-]{2,63})$)" id="id_department_email" maxlength="128" name="department_email" ng-model="rotationRequestData[&#39;department_email&#39;]" type="email" /><ul class="djng-form-control-feedback djng-field-errors" ng-show="rotationRequestForm.department_email.$dirty" ng-cloak><li ng-show="rotationRequestForm['department_email'].$error.email" class="invalid">Enter a valid email address.</li><li ng-show="rotationRequestForm['department_email'].$valid" class="valid"></li></ul><ul class="djng-form-control-feedback djng-field-errors" ng-show="rotationRequestForm.department_email.$pristine" ng-cloak><li ng-show="rotationRequestForm.department_email.$message" class="invalid" ng-bind="rotationRequestForm.department_email.$message"></li></ul></div>
              <div class="has-feedback form-group"><label class="control-label" for="id_department_phone">Phone</label><input class="form-control" id="id_department_phone" maxlength="128" name="department_phone" ng-maxlength="128" ng-model="rotationRequestData[&#39;department_phone&#39;]" type="text" /><ul class="djng-form-control-feedback djng-field-errors" ng-show="rotationRequestForm.department_phone.$dirty" ng-cloak><li ng-show="rotationRequestForm['department_phone'].$error.maxlength" class="invalid">Ensure this value has at most 128 characters</li><li ng-show="rotationRequestForm['department_phone'].$valid" class="valid"></li></ul><ul class="djng-form-control-feedback djng-field-errors" ng-show="rotationRequestForm.department_phone.$pristine" ng-cloak><li ng-show="rotationRequestForm.department_phone.$message" class="invalid" ng-bind="rotationRequestForm.department_phone.$message"></li></ul></div>
              <div class="has-feedback form-group"><label class="control-label" for="id_department_extension">Extension</label><input class="form-control" id="id_department_extension" maxlength="16" name="department_extension" ng-maxlength="16" ng-model="rotationRequestData[&#39;department_extension&#39;]" type="text" /><ul class="djng-form-control-feedback djng-field-errors" ng-show="rotationRequestForm.department_extension.$dirty" ng-cloak><li ng-show="rotationRequestForm['department_extension'].$error.maxlength" class="invalid">Ensure this value has at most 16 characters</li><li ng-show="rotationRequestForm['department_extension'].$valid" class="valid"></li></ul><ul class="djng-form-control-feedback djng-field-errors" ng-show="rotationRequestForm.department_extension.$pristine" ng-cloak><li ng-show="rotationRequestForm.department_extension.$message" class="invalid" ng-bind="rotationRequestForm.department_extension.$message"></li></ul>
              <input class="form-control ng-pristine ng-untouched ng-valid ng-empty" id="id_department" name="department" ng-model="rotationRequestData['department']" type="hidden">
              <input class="form-control ng-pristine ng-untouched ng-valid ng-empty" id="id_is_in_database" name="is_in_database" ng-model="rotationRequestData['is_in_database']" type="hidden"></div>
            </div>

          </div><!-- /.modal-body -->

          <div class="modal-footer">
            <a type="button" class="btn btn-default pull-left" href="#/planner/">Back</a>
            <button type="button" class="btn btn-primary" ng-click="submit()" ng-disabled="{{ form.form_name }}.$invalid">Submit</button>
          </div>

        </div><!-- /.modal-content -->
      </form>
    </div><!-- /.modal-dialog -->
  </div>
</div>